### ISSUE TITLE
decouple start code from CLI

### ISSUE THREAD

**Issue by jdanyow** [gja/cloudflare-worker-local#14]
Opening to continue discussion from https://github.com/gja/cloudflare-worker-local/pull/13#issuecomment-443396377

What do you think about splitting start.js into two files: 
1. cli.js: argv, SIGHUP and file access related code
2. index.js: exports a `start` and `updateWorkerScript` functions, re-exports the worker.js and server.js exports?

```js
import { start, updateWorkerScript } from 'cloudflare-worker-local';

const options = {
  port: 4000,
  workerScript: '... javascript ...',
  upstreamHost: 'localhost:3000',
  kvStores: [],
  workerCount: 1
};

start(options);
...
...
updateWorkerScript('... js ...');
```

This would make the following scenario cleaner / less hacky:

```js
import chokidar from 'chokidar';
import { access, F_OK } from 'fs';

const filename = 'dist/index.js';

let started = false;

async function handler() {
  const exists = await new Promise(resolve => access(filename, F_OK, e => resolve(!e)));
  if (exists && !started) {
    started = true;
    // TEMP: set args expected by cloudflare-worker-local
    process.argv[2] = filename;
    process.argv[3] = 'localhost:7001';
    process.argv[4] = '7000';
    import('cloudflare-worker-local/start.js');
  } else if (exists && started) {
    process.emit('SIGHUP');
  }
}

let timeout = 0;
function debouncedHandler() {
  clearTimeout(timeout);
  timeout = setTimeout(handler, 300);
}

chokidar.watch(filename)
  .on('add', debouncedHandler)
  .on('change', debouncedHandler);
```

**Comment by gja** [comment]
Hmmm, I still think we should be exporting the following things:

- startServer(pathToWorker, {port}) (this automatically will updating the worker on SIGHUP)
- Worker
- startTestServer(workerContents, upstreamBehavior)

I've updated the readme, turns out watching and listening for SIGHUP is actually much easier than I thought.

**Comment by jdanyow** [comment]
In my experience so far using cloudflare-worker-local with packagers like parcel and rollup, nodemon hasn't worked well. It leads to complex npm scripts to ensure the packager has built the worker script prior to starting cloudflare-worker-local. Similar to https://github.com/remy/nodemon/issues/1297 and https://github.com/remy/nodemon/issues/797.

The sighup approach seems to be ok for scenarios where the worker source code is a single javascript file.

For increased flexibility I think it would be great if the CLI related logic (`process.argv`, `SIGHUP` and `fs.readFile(pathToWorker)`) was decoupled from the core logic (start server / update worker).

**Comment by gja** [comment]
I think this will probably be the direction we go in. As a start, I've opened #19, which just exports (by default) Worker and createApp.

**Comment by gja** [comment]
If you want to use chokidar, the new pseudocode would look something like this

```js
const {createApp} = require("cloudflare-worker-local")

const app = createApp(fs.readFileSync("/path/to/worker.js"), {})
app.listen(3000);

chokidhar.watch("/path/to/worker.js")
  .on('change', () => fs.readFile('/path/to/worker.js', buffer => app.updateWorker(bufferToString(buffer))))
```
