### ISSUE TITLE
Support FetchEvent.passThroughOnException()

### ISSUE THREAD

**Issue by rita-liu** [gja/cloudflare-worker-local#36]
Cloudflare worker now supports `FetchEvent.passThroughOnException()` to handle worker exceptions.  

From [official docs](https://developers.cloudflare.com/workers/writing-workers/handling-errors/): 
> Often, if your Worker isn’t doing security-critical activities, it makes sense for it to act as if it’s not installed at all if it errors. This allows you to install logging, tracking, or other minor Workers without fearing they may break your underlying site. This behavior can be toggled on by calling event.passThroughOnException()

There should be at least a copy of this interface to `cloudflare-worker-local` so that valid worker scripts won't fail on local dev.

**Comment by gja** [comment]
Hmmmm. This is a lot of food for thought. I guess the correct way to handle this would be to catch the exception, then re-clone the request and forward it to the backend. At the very least, we should ensure a `big ugly warning` gets printed out when you call passThroughException() to mention that it is not supported at the moment.
