### ISSUE TITLE
Move all program arguments into worker.toml config file

### ISSUE THREAD

**Issue by innovate-invent** [gja/cloudflare-worker-local#47]
Rather than have a horrible mix of environment variables, command line arguments, and worker.toml I propose that it all be consolidated into the new worker.toml file.

The worker.toml file path becomes the only parameter and optionally it can be provided via stdin.

The execution then becomes:
`$ cloudflare-worker-local /path/to/worker.toml`

or: 
`$ cloudflare-worker-local < /path/to/worker.toml`

The stdin option gives the user the option to make the worker.toml file more ephemeral for cloud environments. It also makes it easier to compile the config on the fly:
`$ cat /path/to/worker.toml $(echo '[secret]\nmysecret =' $KUBERNETES_OR_DOCKER_SECRET)  | cloudflare-worker-local`

If this is acceptable will produce a PR

**Comment by gja** [comment]
I'm ok with this. But I think we should support both. Also, I'd personally prefer yml rather than toml.

**Comment by innovate-invent** [comment]
I prefer YAML as well but this goes back to the fact that users will already have the worker.toml and it already has a specification provided by CloudFlare.

Is the file extension enough to disambiguate /path/to/worker.toml and /path/to/worker.js?
I have always had problems with software that relied on file extensions as not all pipelines maintain the file extensions.

**Comment by gja** [comment]
I think that should be fine, though I'm not a fan of it either.

I also wanted to at some point add multiple workers, similar to how Cloudflare does it. (/foo calls worker1, /bar is worker2). This yaml/toml entry point is more scalable as it will eventually allow such scenarios.

I think looking at the file extension would be the best way forward.

**Comment by innovate-invent** [comment]
I may be wrong, but I believe it is one worker per host. The path is passed to the worker to decide its logic while the subdomain determines the worker. It would be totally acceptable to have a separate cloudflare-worker-local instance per worker. I would want to go so far as a separate container per worker so that orchestration can be done per worker-service and scaled at the container level.

**Comment by gja** [comment]
That is not accurate. You can specify regexes both on the host and the path. It is, however, one worker per *request*, ie you cannot cascade from one worker to the other, the first match picks the worker.

**Comment by innovate-invent** [comment]
Ah! I found it. It was in the zone settings and not the worker settings page.
Do you think it makes more sense to do that sort of routing upstream by a loadbalancer or reverse proxy rather than trying to re-implement that functionality?

**Comment by gja** [comment]
I’d prefer to handle it here, mostly because each worker grabs an open port. It will be really annoying to need multiple ports for this

**Comment by innovate-invent** [comment]
How well insulated are the worker environments in your implementation?
I would be worried about it breaking out into other workers, or a single worker bringing down the rest.

**Comment by gja** [comment]
It should be fine. I use vm.context(). IAC, one worker will crash express, and cluster will create another worker.

That said, there is no need to implement multiple workers in the first revision. We can do that in the future as well.

Also, please add your self to contributors.
