### ISSUE TITLE
MINIO_PORT env var doesn't work

### ISSUE THREAD

**Issue by noamokman** [gja/cloudflare-worker-local#63]
Hey,
The env var MINIO_PORT doesn't work, because env vars are string, and the package accepts numbers.
https://github.com/gja/cloudflare-worker-local/blob/78348e4a74594bfe400f6059fcf59475cbbc88e2/app/minio-kv-store.js#L101
We just need to parse it here.

Can you please do it and release a new version?

**Comment by gja** [comment]
could you please submit a PR for this? I'll have this merged quickly

**Comment by gja** [comment]
Sorry @noamokman just haven't had the time to work on this.

**Comment by noamokman** [comment]
No problem, was just closing old issues.
