### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by scrissti** [gja/cloudflare-worker-local#64]
Hi,
I defined some environment variables in the toml file vars = {MAX_BOT_SCORE = "1"} and trying to read it using process.env.MAX_BOT_SCORE but I get a "process is not defined" exception.
Any thoughts?
Thanks

**Comment by jccr** [comment]
The JS VM context that the workers run in does not expose `process.env` and instead the toml vars are exposed as global strings:

From the [docs](https://developers.cloudflare.com/workers/platform/environments#introducing-environments):
> Once a [...] variable [...] via wrangler [...], the string is exposed on the global namespace as type String.

Based on your example:

toml:
```toml
vars = { MAX_BOT_SCORE = "1" }
```

script:
```js
if (MAX_BOT_SCORE === "1") {
  // something
} else {
  // something else
}
```

**Comment by gja** [comment]
Yes, that's right, this package intentionally does not support exporting process. If cloud flare does support this at some point, I'll add support here.

As a side note, if you are using web pack to bundle your script, you can use web pack environment plugin to handle this.
