### ISSUE TITLE
Not possible to set cf-ipcountry header, it is always DEV

### ISSUE THREAD

**Issue by atomin-wr** [gja/cloudflare-worker-local#80]
For context our worker has some logic dependent on user country in order to test this logic  I want to set this header to value different than default 'DEV' value

**Comment by gja** [comment]
ThNk you for raising this bug. I don’t have too much time to work on this,
but I would accept a PR for this functionality.

Tejas

**Comment by hagent** [comment]
@gja I created pull request, but pipeline was failing and I had to make minimal nodejs version 10, I hope it's ok https://github.com/gja/cloudflare-worker-local/pull/82
